# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangfortran_compilergfortranpython2.7
    - CONFIG=osx_c_compilerclangfortran_compilergfortranpython3.6
    - CONFIG=osx_c_compilerclangfortran_compilergfortranpython3.7
    - CONFIG=osx_c_compilertoolchain_cfortran_compilertoolchain_fortpython2.7
    - CONFIG=osx_c_compilertoolchain_cfortran_compilertoolchain_fortpython3.6
    - CONFIG=osx_c_compilertoolchain_cfortran_compilertoolchain_fortpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "1yASBq6SgNnYX5qKMBOosnMMqRBLo54zVzzXmId3E3preL1hrcRStS8o20tvMCBdnUdxfGcty3aVSLbCHSyd/wt1+Pk9W+G0arVzlnwAbJYhqFD+leDP8b22qB0b/CZJTTF920TLkATMZUAcIVCxrqfq325iZJyAY7z/d7KGNMPKTVE+GnRnqAKrg2JNWEdzIdoSm/8jTlADpY6WqBLZvvUWAKTvvCudrlTXFTnJ4TglcZMFZiR37pcdvB4BKw51R3AhRm0Hk58ojqdmOLGWtue6J/IBgAhPDELybrKHauL5MzbM9Q8AXzoxLwIy7o84kYjN97jqQ/mbcMvRDsKFFYPlemUqyi6qBJaHXsGq0dCVmv0QdakIgnEwQV+51CQQ1K3BeAuwPBendTlyQp9gil6C55twqA4ncSPqRoiFIjoO/KlJ8dkffY0p/D3uiTJSc6nFOuFnqyAjFi248AQwTh3XoH67fhY7HXB52n1mPtu6Plzbnvrj/aVMpNw20kh0qBVw6EoeSIJkCFfKQrgom3YSZDLuSeEEYdSwAs8bYjrLgfBzIdIUoiavsbGt9EWtRoLc8ULjpte25lLLXIhg4y9uvPwwvUpyTvZb6/wbGZNjQGJ1/dbboTCNSqXOMuHpWe0HqOobGtKVoJxgGd9icWlfoCBOn3AivcqNh5sbzm4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
